/**:
  $(var gripper_name)_controller:
    ros__parameters:
      gripper_name:        $(var gripper_name)
      mimic_outer_joints:  true
      # Coefficients for converting controller torque values to Newton-meters
      # (Obtained from pyHand 1.0 Manual)
      torque_coefficients: [-2.85, 37.46e-4, -1.708e-6, 2.754e-10]

  joint_state_to_array:
    ros__parameters:
      joints:
        - $(var gripper_name)_left_finger_joint
        - $(var gripper_name)_right_finger_joint
        - $(var gripper_name)_middle_finger_joint
        - $(var gripper_name)_spread_joint

  joint_state_publisher_gui:
    ros__parameters:
      rate: 100
