name: docs
on: push

jobs:
  ros_build:
    runs-on: ubuntu-24.04
    env:
      WS:  /home/runner/work/ros2_docs_ws
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: aist_barrett

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: jazzy

    - name: Apt update and upgrade
      run: |
        sudo apt update
        sudo apt upgrade -y

    - name: Install dependencies
      run: |
        sudo apt install python3-rosdoc2 python3-doxypypy

    - name: Init workspace
      run: |
        mkdir ${WS}
        ln -s ${GITHUB_WORKSPACE} ${WS}/src

    - name: Pre build
      run: |
        source /opt/ros/jazzy/setup.bash
        cd ${WS}/src
        rosdep update
        rosdep install -iy --from-paths ./

    - name: Build documents of aist_barrett
      run: |
        cd ${WS}/src/aist_barrett
        doxygen

    - name: Build documents of aist_barrett_msgs
      run: |
        cd ${WS}/src/aist_barrett/docs
        rosdoc2 build --package-path ../aist_barrett_msgs
        mv ./docs_output/aist_barrett_msgs ./html

    - name: Upload artifact of aist_barrett
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./aist_barrett/docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

permissions:
  contents: write
  pages: write
  id-token: write
