name: lyrical-build
on: push

jobs:
  jazzy-build:
    uses: ./.github/workflows/build.yaml
    with:
      os: ubuntu-26.04
      ros_distro: lyrical
      libbarrett_branch: resolute

permissions:
  contents: write
  pages: write
  id-token: write
